<template>
    <div class="tabbar">
      <div class="iconList">
        <a href="#"><img src="../../static/images/weibo.png"></a>
        <a href="#"><img src="../../static/images/bofang.png"></a>
      </div>
      <div class="scanBox">
        <img src="../../static/images/scanImg.png">
      </div>
      <div class="linkList">
        <router-link to="/index">首页</router-link>
        <router-link to="/index">产品系列</router-link>
        <router-link to="/index">乐手视频</router-link>
        <router-link to="/index">新闻动态</router-link>
        <router-link to="/index">联系我们</router-link>
        <router-link to="/index">关于我们</router-link>
        <router-link to="/index">经销网络</router-link>
      </div>
    </div>
</template>
<script>
    export default {}
</script>
